// THE MOVEMENTS. Data only — no logic, and no import but the type.
//
// Split out of `lib/homeExercises.ts` when the two together passed this repo's
// 500-line ceiling. That file owns the types and every lookup over this array
// and re-exports it, so **every call site still imports `./homeExercises`** and
// nothing addresses this file directly. Append a movement to the list and the
// filters, the progression chains and the manual all pick it up.
//
// Each entry carries: the muscle filter it sits under, its family (the unit the
// manual teaches in), what you need in the room, a difficulty, the rep target,
// the ordered cues, the one mistake that makes the movement stop working, and
// the ids of the easier and harder versions of the same movement.
//
// Muscles are deliberately NOT a field. `lib/exerciseMuscles.ts` maps a name to
// primary/secondary wger ids for the whole app; `musclesOf` delegates to it and
// `homeExercises.test.ts` fails if a name added here resolves to nothing.

import type { HomeExercise } from './homeExercises'

export const HOME_EXERCISES: HomeExercise[] = [
  // ── Horizontal push ────────────────────────────────────────────────────────
  { id: 'wallpushup', name: 'Wall push-ups', muscle: 'chest', family: 'push', equipment: 'none', difficulty: 'beginner', reps: '3×12', harder: 'inclinepushup',
    how: 'Hands on a wall at chest height, body in one line, lower the chest to the wall.',
    cues: ['Hands on the wall at chest height, slightly wider than the shoulders', 'Walk the feet back until the arms are straight and the body is one line', 'Lower the chest to the wall, elbows back at about 45°, then press away'],
    mistake: 'Standing too close, so the arms never straighten and there is nothing to push.' },
  { id: 'inclinepushup', name: 'Incline push-ups', muscle: 'chest', family: 'push', equipment: 'chair', difficulty: 'beginner', reps: '3×10', easier: 'wallpushup', harder: 'kneepushup',
    how: 'Hands on a chair or step — the higher the hands, the less of you to lift.',
    cues: ['Hands on the seat or a step, under the shoulders', 'One straight line from the ears to the heels, ribs down', 'Lower until the chest reaches the edge, then press the floor away'],
    mistake: 'Letting the hips lead on the way up, which turns it into a worm rather than a press.' },
  { id: 'kneepushup', name: 'Knee push-ups', muscle: 'chest', family: 'push', equipment: 'none', difficulty: 'beginner', reps: '3×12', easier: 'inclinepushup', harder: 'pushup',
    how: 'Easier push-up from the knees; keep hips down and core tight.',
    cues: ['Knees down, hands under the shoulders, hips pushed forward so the thighs and trunk are one line', 'Squeeze the glutes — that is what stops the hips sagging', 'Lower the chest, not the head'],
    mistake: 'Sitting the hips back, which shortens the lever and takes the chest out of it.' },
  { id: 'pushup', name: 'Push-ups', muscle: 'chest', family: 'push', equipment: 'none', difficulty: 'intermediate', reps: '3×12', easier: 'kneepushup', harder: 'declinepushup',
    how: 'Hands under shoulders, body in a straight line, lower chest to the floor, elbows ~45°.',
    cues: ['Hands under the shoulders, fingers forward, weight into the whole hand', 'Brace the abs and squeeze the glutes before the first rep', 'Elbows back at about 45° from the ribs, not flared to the sides', 'Chest to the floor, then push the floor away and finish with the shoulder blades apart'],
    mistake: 'Elbows at 90° to the body. It feels wider and stronger and it is the position the shoulder has least to give in.' },
  { id: 'widepushup', name: 'Wide push-ups', muscle: 'chest', family: 'push', equipment: 'none', difficulty: 'intermediate', reps: '3×10', easier: 'pushup', harder: 'archerpushup',
    how: 'Hands a hand-width wider than normal — more chest, shorter range.',
    cues: ['Hands one hand-width wider than the shoulders', 'Same brace, same straight line', 'Stop when the upper arms reach parallel with the floor'],
    mistake: 'Going as wide as the arms allow and chasing depth there at the same time.' },
  { id: 'diamondpushup', name: 'Diamond push-ups', muscle: 'arms', family: 'push', equipment: 'none', difficulty: 'advanced', reps: '3×8', easier: 'pushup',
    how: 'Index fingers and thumbs touching under the chest — the triceps version.',
    cues: ['Thumbs and index fingers together, hands under the sternum', 'Elbows stay close to the ribs the whole way down', 'Lower the chest to the hands, not the hands to the chest'],
    mistake: 'Letting the elbows drift out, which quietly turns it back into a narrow push-up.' },
  { id: 'declinepushup', name: 'Decline push-ups', muscle: 'chest', family: 'push', equipment: 'chair', difficulty: 'advanced', reps: '3×10', easier: 'pushup', harder: 'archerpushup',
    how: 'Feet on a chair — more of your weight over the hands, and more shoulder.',
    cues: ['Feet on the seat, hands on the floor under the shoulders', 'Keep the ribs down; the higher the feet the more the lower back wants to arch', 'Lower the chest between the hands'],
    mistake: 'Raising the feet so high the movement becomes an overhead press done badly.' },
  { id: 'archerpushup', name: 'Archer push-ups', muscle: 'chest', family: 'push', equipment: 'none', difficulty: 'advanced', reps: '3×6/side', easier: 'widepushup',
    how: 'Wide hands, lower toward one hand while the other arm straightens — half a one-arm push-up.',
    cues: ['Hands wide, feet wide for balance', 'Bend one arm and shift the chest over that hand; the far arm straightens but stays on the floor', 'Press back to the middle before changing sides'],
    mistake: 'Twisting the hips to reach the floor instead of bending the working arm.' },
  { id: 'dbfloorpress', name: 'Dumbbell floor press', muscle: 'chest', family: 'push', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×10', harder: 'dbbenchpress',
    how: 'Press from the floor — the floor caps the range, which is the point.',
    cues: ['On your back, knees bent, dumbbells over the lower chest', 'Elbows at about 45°, triceps touch down and stop', 'Press up and slightly together, wrists stacked over the elbows'],
    mistake: 'Bouncing the elbows off the floor to start the next rep.' },
  { id: 'dbbenchpress', name: 'Dumbbell bench press', muscle: 'chest', family: 'push', equipment: 'bench', difficulty: 'intermediate', reps: '3×10', easier: 'dbfloorpress',
    how: 'Flat bench, dumbbells over the chest, press up and slightly together.',
    cues: ['Shoulder blades pulled back and down into the bench, feet planted', 'Lower until the upper arms reach bench level', 'Press without letting the shoulders roll forward at the top'],
    mistake: 'Chasing a deeper stretch past bench level, where the shoulder has nothing holding it.' },
  { id: 'dbfly', name: 'Dumbbell fly', muscle: 'chest', family: 'push', equipment: 'bench', difficulty: 'intermediate', reps: '3×12',
    how: 'Soft elbows, open the arms wide, close them like a hug — light weight, slow.',
    cues: ['Elbows slightly bent and that angle never changes', 'Open until the chest stretches, no further', 'Close along the same arc and squeeze at the top'],
    mistake: 'Treating it as a press with straight arms — the weight goes up and the chest stops working.' },
  { id: 'bandchestpress', name: 'Band chest press', muscle: 'chest', family: 'push', equipment: 'band', difficulty: 'beginner', reps: '3×15',
    how: 'Band behind the back at chest height, press the handles forward and together.',
    cues: ['Band across the upper back, a handle in each hand at armpit height', 'Step one foot forward for a base', 'Press forward and in until the knuckles nearly meet, then come back slowly'],
    mistake: 'Letting the band snap you back — the return is half the work.' },

  // ── Vertical push ──────────────────────────────────────────────────────────
  { id: 'inclinepike', name: 'Incline pike push-ups', muscle: 'shoulders', family: 'overhead', equipment: 'none', difficulty: 'beginner', reps: '3×10', harder: 'pikepushup',
    how: 'Hips high but hands on the floor and feet low — the gentle end of the pike.',
    cues: ['From a push-up, walk the feet in until the hips are above the shoulders', 'Keep the legs as straight as the hamstrings allow', 'Lower the crown of the head toward the floor between the hands'],
    mistake: 'Bending the hips and calling it a pike while the press stays horizontal.' },
  { id: 'pikepushup', name: 'Pike push-ups', muscle: 'shoulders', family: 'overhead', equipment: 'none', difficulty: 'intermediate', reps: '3×8', easier: 'inclinepike', harder: 'elevatedpike',
    how: 'Hips high (inverted V), lower the crown of your head toward the floor.',
    cues: ['Hands shoulder-width, hips stacked over the hands, heels up', 'Elbows track back and slightly out, not flared flat', 'Touch the floor in front of the hands, then press straight up'],
    mistake: 'Craning the neck to touch the floor rather than bending the arms.' },
  { id: 'elevatedpike', name: 'Elevated pike push-ups', muscle: 'shoulders', family: 'overhead', equipment: 'chair', difficulty: 'advanced', reps: '3×6', easier: 'pikepushup', harder: 'wallhspu',
    how: 'Feet on a chair so the torso is nearly vertical — most of your weight overhead.',
    cues: ['Feet on the seat, hands on the floor, hips directly over the shoulders', 'Ribs down so the back does not arch to find the position', 'Lower the head toward the floor, elbows back'],
    mistake: 'Letting the hips drift behind the hands, which takes the load back off the shoulders.' },
  { id: 'wallhspu', name: 'Wall handstand push-ups', muscle: 'shoulders', family: 'overhead', equipment: 'none', difficulty: 'advanced', reps: '3×4', easier: 'elevatedpike',
    how: 'Chest-to-wall or back-to-wall handstand, bend and press. Hold the position before you press it.',
    cues: ['Hold a wall handstand for 30s before attempting a rep', 'Squeeze the glutes and the abs so the body is one line, not a banana', 'Lower under control until the head nears the floor, then press to straight arms'],
    mistake: 'Kicking up and pressing before the hold is solid, so every rep is a balance save.' },
  { id: 'dbshoulderpress', name: 'Dumbbell shoulder press', muscle: 'shoulders', family: 'overhead', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×10', harder: 'dbarnold',
    how: 'Dumbbells at shoulder height, press overhead until the arms are straight.',
    cues: ['Stand tall, ribs down, glutes and abs braced so the back does not arch', 'Start with the dumbbells at ear height, elbows slightly in front of the body', 'Press until the arms are straight and the weights are over the ears, not in front of them'],
    mistake: 'Leaning back to get the weight up, which turns an overhead press into an incline press.' },
  { id: 'dbarnold', name: 'Arnold press', muscle: 'shoulders', family: 'overhead', equipment: 'dumbbell', difficulty: 'intermediate', reps: '3×10', easier: 'dbshoulderpress',
    how: 'Start palms-in at the chin, rotate out as you press — the whole shoulder in one rep.',
    cues: ['Palms facing you, dumbbells at chin height', 'Rotate the palms out as the arms rise, finishing palms forward overhead', 'Reverse the rotation on the way down'],
    mistake: 'Rotating at the bottom and pressing straight up — the rotation has to happen under load.' },
  { id: 'dblateralraise', name: 'Lateral raises', muscle: 'shoulders', family: 'overhead', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×15',
    how: 'Arms out to the sides to shoulder height, little-finger leading, slow down.',
    cues: ['Slight bend in the elbows, dumbbells beside the thighs', 'Lead with the elbows out to the side, stopping at shoulder height', 'Lower over two or three seconds'],
    mistake: 'Swinging the body to launch the weight — go lighter and the shoulder actually gets the set.' },
  { id: 'bandoverheadpress', name: 'Band overhead press', muscle: 'shoulders', family: 'overhead', equipment: 'band', difficulty: 'beginner', reps: '3×15',
    how: 'Stand on the band, press the handles overhead — hardest at the top, where a dumbbell is easiest.',
    cues: ['Both feet on the band, handles at shoulder height', 'Brace the trunk; the band pulls you into a backward lean', 'Press to straight arms over the ears and resist the pull down'],
    mistake: 'Standing on a band so short the shoulders cannot reach the start position.' },
  { id: 'kbpress', name: 'Kettlebell press', muscle: 'shoulders', family: 'overhead', equipment: 'kettlebell', difficulty: 'intermediate', reps: '3×6/side',
    how: 'One bell in the rack position, press overhead, keep the whole body tight.',
    cues: ['Bell in the rack: wrist straight, forearm vertical, elbow into the ribs', 'Squeeze the glutes and the free fist — tension travels', 'Press up and slightly out so the bell finishes over the shoulder'],
    mistake: 'A bent-back wrist, which puts the bell behind the forearm and the strain in the joint.' },

  // ── Vertical pull ──────────────────────────────────────────────────────────
  { id: 'deadhang', name: 'Dead hang', muscle: 'back', family: 'pull', equipment: 'bar', difficulty: 'beginner', reps: '3×30s', harder: 'scapularpull',
    how: 'Hang from the bar, shoulders active, grip hard — the base for everything on the bar.',
    cues: ['Full grip, pinky knuckle over the top of the bar', 'Hang with the arms straight but the shoulders not shrugged to the ears', 'Legs together, toes pointed, ribs down'],
    mistake: 'Hanging completely slack, which trains the grip and nothing that pulls.' },
  { id: 'scapularpull', name: 'Scapular pulls', muscle: 'back', family: 'pull', equipment: 'bar', difficulty: 'beginner', reps: '3×8', easier: 'deadhang', harder: 'negativepullup',
    how: 'From a dead hang, pull the shoulder blades down with no elbow bend.',
    cues: ['Start from a full dead hang with the arms completely straight', 'Pull the shoulders down and back — the chest rises an inch and the elbows do not move', 'Pause, then let the shoulders rise under control'],
    mistake: 'Bending the elbows, which makes it a short pull-up and skips the thing being trained.' },
  { id: 'negativepullup', name: 'Pull-up negatives', muscle: 'back', family: 'pull', equipment: 'bar', difficulty: 'beginner', reps: '3×5', easier: 'scapularpull', harder: 'chinup',
    how: 'Step or jump to the top, then resist a slow 3–7 second descent to a full hang.',
    cues: ['Start with the chin over the bar, elbows at the ribs', 'Lower over three to seven seconds, fighting the whole way', 'Finish at a full dead hang, then step back up — do not drop'],
    mistake: 'Dropping the last third, which is the range a first pull-up is actually missing.' },
  { id: 'bandlatpulldown', name: 'Band lat pulldown', muscle: 'back', family: 'pull', equipment: 'band', difficulty: 'beginner', reps: '3×15',
    how: 'Band anchored high, kneel and pull the handles to the collarbones.',
    cues: ['Anchor overhead, kneel far enough back for tension at the top', 'Start the pull by dropping the shoulder blades, then bend the elbows', 'Pull the hands to the collarbones, elbows down to the ribs'],
    mistake: 'Leaning back so far it becomes a row — the band should pull you up, not forward.' },
  { id: 'chinup', name: 'Chin-ups', muscle: 'back', family: 'pull', equipment: 'bar', difficulty: 'intermediate', reps: '3×6', easier: 'negativepullup', harder: 'pullup',
    how: 'Palms toward you — the biceps help, so it is the easier of the two grips.',
    cues: ['Underhand grip, shoulder-width, full hang to start', 'Brace the abs and squeeze the glutes; legs stay still', 'Pull the elbows to the ribs until the chin clears the bar, then lower to a full hang'],
    mistake: 'Kicking the legs to start the rep. A kip is a different exercise; see the Pull-ups page.' },
  { id: 'pullup', name: 'Pull-ups', muscle: 'back', family: 'pull', equipment: 'bar', difficulty: 'advanced', reps: '3×5', easier: 'chinup',
    how: 'Overhand grip, pull with the elbows until the chin clears the bar, lower to a full hang.',
    cues: ['Overhand grip just outside the shoulders, pinky knuckle over the bar', 'Tuck the pelvis and tighten the abs before you leave the floor', 'Pull the elbows down to the ribs — think elbows, not hands', 'Chin over the bar without craning, then lower all the way down'],
    mistake: 'Stopping short at the bottom. Half a rep up is still a rep; half a rep down is a rep you did not do.' },
  { id: 'dbpullover', name: 'Dumbbell pullover', muscle: 'back', family: 'pull', equipment: 'bench', difficulty: 'intermediate', reps: '3×12',
    how: 'One dumbbell over the chest, arms nearly straight, lower it behind the head.',
    cues: ['Lie across or along a bench, both hands on one dumbbell over the chest', 'Elbows slightly bent and fixed', 'Lower behind the head until the lats stretch, then pull back over the chest'],
    mistake: 'Letting the ribs flare and arching off the bench to get more range.' },

  // ── Horizontal pull ────────────────────────────────────────────────────────
  { id: 'bandrow', name: 'Band row', muscle: 'back', family: 'row', equipment: 'band', difficulty: 'beginner', reps: '3×15', harder: 'dbrow',
    how: 'Band anchored at chest height, pull the handles to the ribs, squeeze the blades.',
    cues: ['Anchor at chest height, step back for tension, soft knees', 'Start by pulling the shoulder blades together', 'Elbows past the ribs, then return slowly to full arm extension'],
    mistake: 'Shrugging the shoulders up to the ears instead of back.' },
  { id: 'bandpullapart', name: 'Band pull-aparts', muscle: 'back', family: 'row', equipment: 'band', difficulty: 'beginner', reps: '3×20',
    how: 'Band in both hands at chest height, pull it apart until it touches the chest.',
    cues: ['Arms straight out in front at chest height, band taut', 'Pull apart by squeezing the shoulder blades together', 'Return slowly, keeping the arms straight'],
    mistake: 'Bending the elbows, which lets the arms do what the upper back is there to do.' },
  { id: 'dbrow', name: 'One-arm dumbbell row', muscle: 'back', family: 'row', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×10/side', easier: 'bandrow', harder: 'invertedrow',
    how: 'Hinge with one hand on a support, row the dumbbell to the hip.',
    cues: ['Hinge until the back is nearly parallel to the floor, one hand on a chair or bench', 'Let the arm hang straight down, then pull the shoulder blade back first', 'Row to the hip, not to the shoulder — elbow past the ribs'],
    mistake: 'Twisting the torso up with each rep, which moves the weight with the spine rather than the back.' },
  { id: 'dbbentoverrow', name: 'Bent-over row', muscle: 'back', family: 'row', equipment: 'dumbbell', difficulty: 'intermediate', reps: '3×10',
    how: 'Hinge to about 45°, both dumbbells row to the ribs, back flat throughout.',
    cues: ['Hinge at the hips with a flat back, knees soft, dumbbells hanging', 'Brace hard — the trunk holding the angle is most of this exercise', 'Row both to the lower ribs, pause, lower fully'],
    mistake: 'Standing up a little on every rep, so the hinge gets shallower as the set goes on.' },
  { id: 'dbreversefly', name: 'Reverse fly', muscle: 'back', family: 'row', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×15',
    how: 'Hinge forward, open the arms out to the sides — the back of the shoulder.',
    cues: ['Hinge forward, light dumbbells hanging, elbows slightly bent', 'Open out to the sides to shoulder height, thumbs up', 'Lower slowly; this is a small movement done well, not a big one done fast'],
    mistake: 'Going heavy, which recruits the whole back and leaves the rear shoulder untouched.' },
  { id: 'invertedrow', name: 'Inverted row', muscle: 'back', family: 'row', equipment: 'bar', difficulty: 'intermediate', reps: '3×10', easier: 'dbrow',
    how: 'Hang under a low bar or a sturdy table, body straight, pull the chest to it.',
    cues: ['Grip the bar at chest width, heels on the floor, body in one line', 'Squeeze the glutes so the hips do not sag', 'Pull the chest to the bar, elbows back, then lower to straight arms'],
    mistake: 'Bending at the hips, which shortens the body and makes the row easier without saying so.' },
  { id: 'superman', name: 'Superman', muscle: 'back', family: 'row', equipment: 'none', difficulty: 'beginner', reps: '3×12',
    how: 'Face down, lift arms and legs together, squeeze the lower back, pause.',
    cues: ['Face down, arms overhead, legs straight', 'Lift the arms, chest and legs a few inches and hold for a second', 'Keep the neck neutral — look at the floor, not forward'],
    mistake: 'Hauling the chest as high as it goes, which hinges the lower back instead of extending it.' },

  // ── Squat ──────────────────────────────────────────────────────────────────
  { id: 'chairsquat', name: 'Chair squats', muscle: 'legs', family: 'squat', equipment: 'chair', difficulty: 'beginner', reps: '3×12', harder: 'squat',
    how: 'Sit back to a chair, touch it, stand up — the depth is decided for you.',
    cues: ['Stand a foot in front of the chair, feet shoulder-width', 'Sit the hips back and down until they touch the seat', 'Drive through the whole foot to stand, finishing with the hips under the ribs'],
    mistake: 'Flopping onto the seat instead of touching it — the control is the exercise.' },
  { id: 'squat', name: 'Bodyweight squats', muscle: 'legs', family: 'squat', equipment: 'none', difficulty: 'beginner', reps: '3×15', easier: 'chairsquat', harder: 'gobletsquat',
    how: 'Feet shoulder-width, sit back and down, knees track over toes, chest up.',
    cues: ['Feet shoulder-width, toes forward or slightly out', 'Brace the abs, then break at the hips and knees together', 'Knees travel over the toes, heels stay down', 'Go as deep as you can keep a flat back, then stand and squeeze the glutes'],
    mistake: 'Keeping the knees behind the toes on purpose. It forces the back to take the angle instead.' },
  { id: 'gobletsquat', name: 'Goblet squat', muscle: 'legs', family: 'squat', equipment: 'kettlebell', difficulty: 'intermediate', reps: '3×12', easier: 'squat', harder: 'splitsquat',
    how: 'Hold a bell or dumbbell at the chest — the load in front keeps the chest up for you.',
    cues: ['Bell held at the sternum, elbows tucked in', 'Squat between the legs, letting the elbows pass inside the knees', 'Keep the bell against the chest the whole time'],
    mistake: 'Letting the weight drift away from the chest, which pulls you forward and loads the back.' },
  { id: 'jumpsquat', name: 'Jump squats', muscle: 'legs', family: 'squat', equipment: 'none', difficulty: 'intermediate', reps: '3×10', easier: 'squat',
    how: 'Squat to about half depth and jump; land soft, absorb, reset.',
    cues: ['Quarter to half squat, then jump as high as you can', 'Land on the whole foot and absorb by bending the hips and knees', 'Reset your stance between reps rather than bouncing'],
    mistake: 'Landing stiff-legged and loud. Soft landings are the point; if they get loud, end the set.' },
  { id: 'pistolsquat', name: 'Pistol squat', muscle: 'legs', family: 'squat', equipment: 'none', difficulty: 'advanced', reps: '3×5/side', easier: 'splitsquat',
    how: 'One leg, the other out in front, all the way down and back up.',
    cues: ['Hold something light for balance until the pattern is yours', 'Reach the free leg forward and sit straight down on the standing heel', 'Keep the standing heel flat — rising onto the toes is the balance going'],
    mistake: 'Chasing the full version before a box pistol to a knee-height seat is comfortable.' },
  { id: 'wallsit', name: 'Wall sit', muscle: 'legs', family: 'squat', equipment: 'none', difficulty: 'beginner', reps: '3×40s',
    how: 'Back flat on a wall, thighs parallel to the floor, hold.',
    cues: ['Back and shoulders flat on the wall, feet shoulder-width', 'Slide down until the thighs are parallel with the floor, knees over the ankles', 'Breathe normally — holding your breath is what makes this feel impossible'],
    mistake: 'Stopping above parallel, where the legs are barely working and only time passes.' },
  { id: 'calfraise', name: 'Calf raises', muscle: 'legs', family: 'squat', equipment: 'none', difficulty: 'beginner', reps: '3×20',
    how: 'Rise onto the balls of your feet, pause at the top, lower slowly.',
    cues: ['Stand tall, fingertips on a wall for balance only', 'Rise as high as the ankles allow and pause for a count', 'Lower over two seconds until the heels touch'],
    mistake: 'Bouncing, which uses the tendon and skips the muscle. Pause at both ends.' },

  // ── Single leg ─────────────────────────────────────────────────────────────
  { id: 'reverselunge', name: 'Reverse lunges', muscle: 'legs', family: 'lunge', equipment: 'none', difficulty: 'beginner', reps: '3×10/side', harder: 'lunge',
    how: 'Step back into a lunge — gentler on the knees than forward lunges.',
    cues: ['Stand tall, step one foot straight back', 'Lower until both knees are about 90°, front shin vertical', 'Push through the front heel to stand, bringing the back foot in'],
    mistake: 'A short step back, which puts the front knee far past the toes and the weight on the kneecap.' },
  { id: 'lunge', name: 'Forward lunges', muscle: 'legs', family: 'lunge', equipment: 'none', difficulty: 'intermediate', reps: '3×10/side', easier: 'reverselunge', harder: 'walkinglunge',
    how: 'Step forward, both knees ~90°, push through the front heel to stand.',
    cues: ['Step forward far enough that both knees reach 90°', 'Torso upright, ribs over hips', 'Push back through the front heel to the start'],
    mistake: 'Leaning forward over the front leg, which hands the work to the lower back.' },
  { id: 'walkinglunge', name: 'Walking lunges', muscle: 'legs', family: 'lunge', equipment: 'none', difficulty: 'intermediate', reps: '3×12/side', easier: 'lunge',
    how: 'Lunge forward and keep walking — no reset between reps.',
    cues: ['Step, sink to 90°, then drive forward into the next step', 'Keep the torso upright through the transition', 'Count reps per leg, not steps'],
    mistake: 'Rushing the transition and bobbing, so no rep reaches depth.' },
  { id: 'sidelunge', name: 'Lateral lunges', muscle: 'legs', family: 'lunge', equipment: 'none', difficulty: 'beginner', reps: '3×10/side',
    how: 'Step wide to one side, sit back on that hip, the other leg stays straight.',
    cues: ['Step wide, both feet pointing forward', 'Sit the hips back onto the stepping leg; the far leg stays straight', 'Push off to return to a narrow stance'],
    mistake: 'Turning the stepping foot out, which makes it a rotated lunge and misses the inner thigh.' },
  { id: 'splitsquat', name: 'Split squat', muscle: 'legs', family: 'lunge', equipment: 'none', difficulty: 'intermediate', reps: '3×10/side', harder: 'bulgarian',
    how: 'Feet already split, drop straight down and back up — all the reps on one leg.',
    cues: ['Set the stance once: front foot flat, back heel up, feet a stride apart', 'Lower straight down until the back knee nearly touches', 'Drive up through the front foot without moving the stance'],
    mistake: 'Drifting forward each rep until the back leg is doing the work.' },
  { id: 'bulgarian', name: 'Bulgarian split squat', muscle: 'legs', family: 'lunge', equipment: 'bench', difficulty: 'advanced', reps: '3×8/side', easier: 'splitsquat',
    how: 'Back foot on a bench or chair, lower straight down on the front leg.',
    cues: ['Top of the back foot on the seat, front foot far enough forward for a vertical shin at the bottom', 'Lower straight down, torso slightly forward over the front hip', 'Push through the front foot to stand'],
    mistake: 'Standing too close to the bench, which pins the front knee past the toes.' },
  { id: 'stepup', name: 'Step-ups', muscle: 'glutes', family: 'lunge', equipment: 'chair', difficulty: 'beginner', reps: '3×10/side',
    how: 'Step up onto a knee-height surface, stand fully, lower under control.',
    cues: ['Whole foot on the step, knee-height or lower to begin', 'Drive through the stepping leg — the back leg does not push off', 'Lower slowly until the back foot touches, then go again'],
    mistake: 'Pushing off the bottom foot, which is a hop with extra steps.' },
  { id: 'dblunge', name: 'Dumbbell lunges', muscle: 'legs', family: 'lunge', equipment: 'dumbbell', difficulty: 'intermediate', reps: '3×10/side',
    how: 'A dumbbell in each hand, reverse lunge — the easiest way to load a single leg at home.',
    cues: ['Dumbbells at the sides, shoulders back', 'Same reverse lunge: step back, both knees to 90°, front heel drives', 'Let the arms hang; do not swing them for momentum'],
    mistake: 'Going heavier than the balance allows, so every rep is a save rather than a set.' },

  // ── Hip hinge ──────────────────────────────────────────────────────────────
  { id: 'glutebridge', name: 'Glute bridge', muscle: 'glutes', family: 'hinge', equipment: 'none', difficulty: 'beginner', reps: '3×15', harder: 'slglutebridge',
    how: 'On your back, drive hips up squeezing glutes, ribs down.',
    cues: ['On your back, heels close to the hips, arms flat', 'Tuck the pelvis, then drive the hips up by squeezing the glutes', 'Stop where the hips, knees and shoulders line up — do not arch past it'],
    mistake: 'Arching the lower back to get higher, which feels like more range and is less glute.' },
  { id: 'slglutebridge', name: 'Single-leg glute bridge', muscle: 'glutes', family: 'hinge', equipment: 'none', difficulty: 'intermediate', reps: '3×12/side', easier: 'glutebridge', harder: 'hipthrust',
    how: 'One foot down, the other knee hugged in, drive up on one leg.',
    cues: ['One heel close to the hip, the other knee pulled to the chest', 'Drive up without letting the hips tilt — keep them level', 'Lower until the hip touches, then go again'],
    mistake: 'Letting the free leg swing to help. Hold it still and the glute has to do it.' },
  { id: 'hipthrust', name: 'Hip thrust', muscle: 'glutes', family: 'hinge', equipment: 'bench', difficulty: 'intermediate', reps: '3×12', easier: 'slglutebridge',
    how: 'Shoulders on a bench, feet planted, drive the hips to level.',
    cues: ['Upper back across the bench, feet flat, shins vertical at the top', 'Chin tucked, ribs down, then drive the hips up to level', 'Hold a dumbbell across the hips when bodyweight gets easy'],
    mistake: 'Finishing with a back arch rather than a glute squeeze — the top is level, not high.' },
  { id: 'dbrdl', name: 'Romanian deadlift', muscle: 'glutes', family: 'hinge', equipment: 'dumbbell', difficulty: 'intermediate', reps: '3×10', harder: 'dbslrdl',
    how: 'Push the hips back with a flat back, dumbbells slide down the thighs, stand by squeezing the glutes.',
    cues: ['Stand tall, dumbbells in front of the thighs, knees softly bent and then still', 'Push the hips back and let the weights travel down the legs', 'Stop when the hamstrings tighten or the back starts to round, whichever comes first', 'Stand by driving the hips forward'],
    mistake: 'Squatting instead of hinging. If the knees bend more on the way down, the hips are not moving back.' },
  { id: 'dbslrdl', name: 'Single-leg RDL', muscle: 'glutes', family: 'hinge', equipment: 'dumbbell', difficulty: 'advanced', reps: '3×8/side', easier: 'dbrdl',
    how: 'One leg down, hinge forward, the free leg extends behind as a counterweight.',
    cues: ['Weight in the opposite hand to the standing leg', 'Hinge forward and let the free leg rise straight behind you', 'Keep the hips square — the rising leg wants to open out'],
    mistake: 'Rotating the hip open, which turns a hinge into a twist.' },
  { id: 'kbdeadlift', name: 'Kettlebell deadlift', muscle: 'glutes', family: 'hinge', equipment: 'kettlebell', difficulty: 'beginner', reps: '3×12', harder: 'kbswing',
    how: 'Bell between the feet, hinge, grip, stand up tall — the swing without the swing.',
    cues: ['Bell between the arches, feet hip-width', 'Push the hips back and reach down; the back stays flat', 'Stand by driving the floor away and squeezing the glutes at the top'],
    mistake: 'Lifting with the arms and a rounded back instead of standing the hips up.' },
  { id: 'kbswing', name: 'Kettlebell swing', muscle: 'full body', family: 'hinge', equipment: 'kettlebell', difficulty: 'intermediate', reps: '5×10', easier: 'kbdeadlift',
    how: 'Hike the bell back, snap the hips forward — the arms only steer. Chest height is high enough.',
    cues: ['Start with the bell a foot in front; hinge, grip it and hike it back between the legs', 'Snap the hips forward and stand tall — the bell floats, you do not lift it', 'At the top: glutes tight, abs tight, arms loose, bell about chest height', 'Let it fall, catch the hinge late, and go again'],
    mistake: 'Squatting and lifting the bell with the shoulders. A swing is a hinge thrown fast, not a front raise.' },
  { id: 'bandgoodmorning', name: 'Band good morning', muscle: 'glutes', family: 'hinge', equipment: 'band', difficulty: 'beginner', reps: '3×15',
    how: 'Band under the feet and over the neck, hinge forward against it.',
    cues: ['Band looped under both feet and across the upper back', 'Soft knees, then hinge forward with a flat back', 'Stand by driving the hips forward against the band'],
    mistake: 'Rounding the upper back under the band instead of hinging at the hip.' },
  { id: 'donkeykick', name: 'Donkey kicks', muscle: 'glutes', family: 'hinge', equipment: 'none', difficulty: 'beginner', reps: '3×12/side',
    how: 'On all fours, drive one heel toward the ceiling with the knee bent.',
    cues: ['On all fours, back flat, abs braced', 'Drive one heel up with the knee bent to 90°', 'Stop when the hip starts to rotate — height past that comes from the spine'],
    mistake: 'Arching the lower back to kick higher, which takes the glute out of it entirely.' },

  // ── Core ───────────────────────────────────────────────────────────────────
  { id: 'deadbug', name: 'Dead bug', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'beginner', reps: '3×10/side', harder: 'plank',
    how: 'On your back, lower one arm and the opposite leg while the lower back stays flat.',
    cues: ['On your back, knees over hips, arms straight up', 'Press the lower back into the floor and keep it there', 'Lower one arm overhead and the opposite leg; return and swap'],
    mistake: 'Letting the lower back lift off the floor. When it does, that was the end of the set.' },
  { id: 'plank', name: 'Plank', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'beginner', reps: '3×45s', easier: 'deadbug', harder: 'hollowhold',
    how: 'Forearms down, body straight, brace the core — no sagging hips.',
    cues: ['Forearms down, elbows under the shoulders, feet hip-width', 'Tuck the pelvis, squeeze the glutes, pull the ribs down', 'Push the floor away through the forearms and breathe'],
    mistake: 'Holding a sagging plank for longer. Thirty honest seconds beats two slack minutes.' },
  { id: 'sideplank', name: 'Side plank', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'intermediate', reps: '3×30s/side',
    how: 'On one forearm, stack feet, lift hips, hold; switch sides.',
    cues: ['Elbow under the shoulder, feet stacked or staggered', 'Lift the hips until the body is one straight line from ear to ankle', 'Press the bottom shoulder away from the ear'],
    mistake: 'Letting the hips drift back, which turns a side plank into a comfortable lean.' },
  { id: 'hollowhold', name: 'Hollow hold', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'advanced', reps: '3×20s', easier: 'plank',
    how: 'On your back, shoulders and legs off the floor, lower back pressed down.',
    cues: ['Press the lower back flat into the floor first', 'Lift the shoulders and legs only as far as the back stays flat', 'Arms by the ears when that is holdable, tucked in before then'],
    mistake: 'Lifting the legs high and arching, which is the opposite shape to the one being trained.' },
  { id: 'birddog', name: 'Bird dog', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'beginner', reps: '3×10/side',
    how: 'On all fours, extend opposite arm and leg, keep hips level.',
    cues: ['On all fours, back flat, abs braced', 'Extend one arm and the opposite leg to horizontal, no higher', 'Keep the hips square — imagine a glass of water on the lower back'],
    mistake: 'Rotating the hip up with the rising leg, which is the movement this exercise exists to resist.' },
  { id: 'bicycle', name: 'Bicycle crunches', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'beginner', reps: '3×20',
    how: 'Opposite elbow to knee, extend the other leg, slow and controlled.',
    cues: ['Hands light behind the head, elbows wide', 'Rotate the ribs toward the opposite knee, not the elbow toward it', 'Extend the other leg long and low'],
    mistake: 'Pulling the head with the hands, which moves the neck and not the trunk.' },
  { id: 'russiantwist', name: 'Russian twists', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'intermediate', reps: '3×20',
    how: 'Seated, lean back, rotate the torso side to side, heels up to progress.',
    cues: ['Sit tall, lean back to about 45°, flat back', 'Rotate from the ribs and let the head follow', 'Heels down to start; lift them when the back stays flat throughout'],
    mistake: 'Swinging the arms while the torso stays still — the hands move and nothing is trained.' },
  { id: 'lyinglegraise', name: 'Lying leg raises', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'intermediate', reps: '3×12', harder: 'hanginglegraise',
    how: 'On your back, hands under the hips, raise straight legs without arching.',
    cues: ['Press the lower back down, hands under the hips if it helps', 'Raise straight legs to vertical, then lower under control', 'Stop lowering where the back starts to lift — that is your range today'],
    mistake: 'Dropping the legs and bouncing off the bottom, which loads the lower back.' },
  { id: 'hanginglegraise', name: 'Hanging leg raises', muscle: 'core', family: 'core', equipment: 'bar', difficulty: 'advanced', reps: '3×10', easier: 'lyinglegraise',
    how: 'Hollow hang, raise straight legs toward the bar without swinging.',
    cues: ['Hang with active shoulders in a slight hollow', 'Raise straight legs as high as control allows, ideally toes to the bar', 'Lower slowly — no swing on the way down, or the next rep is a kip'],
    mistake: 'Using the swing from the last rep. Stop dead between reps and start each one from a hang.' },
  { id: 'pallofpress', name: 'Pallof press', muscle: 'core', family: 'core', equipment: 'band', difficulty: 'beginner', reps: '3×10/side',
    how: 'Band anchored at the side, press straight out and refuse to rotate.',
    cues: ['Stand side-on to the anchor, band at the sternum, feet shoulder-width', 'Press straight out and hold for a breath — the band is trying to turn you', 'Return to the chest without letting the ribs rotate'],
    mistake: 'Standing too close, so there is no tension to resist and the arms just extend.' },
  { id: 'suitcasecarry', name: 'Suitcase carry', muscle: 'core', family: 'core', equipment: 'kettlebell', difficulty: 'beginner', reps: '3×30s/side',
    how: 'One weight in one hand, walk tall — the trunk stops you tipping.',
    cues: ['One bell or dumbbell in one hand, stand tall, shoulders level', 'Walk with short steps, ribs stacked over hips', 'Do not lean away from the weight to balance it'],
    mistake: 'Leaning sideways, which balances the load and skips the exercise.' },
  { id: 'mountainclimber', name: 'Mountain climbers', muscle: 'core', family: 'core', equipment: 'none', difficulty: 'intermediate', reps: '3×30s',
    how: 'Plank position, drive knees to chest alternately, hips low.',
    cues: ['Strong plank first: hands under shoulders, hips level', 'Drive one knee toward the chest and switch', 'Keep the hips low and the shoulders over the hands as the pace rises'],
    mistake: 'The hips rising into a pike as it gets hard, which makes it a cardio drill with no core in it.' },

  // ── Conditioning ───────────────────────────────────────────────────────────
  { id: 'jumpingjack', name: 'Jumping jacks', muscle: 'cardio', family: 'conditioning', equipment: 'none', difficulty: 'beginner', reps: '3×40',
    how: 'Jump feet out while arms go overhead; steady rhythm.',
    cues: ['Land on the whole foot with soft knees', 'Arms all the way overhead, not to shoulder height', 'Pick a rhythm you can hold for the whole set'],
    mistake: 'Half-raising the arms as fatigue arrives, which quietly removes the shoulders.' },
  { id: 'highknees', name: 'High knees', muscle: 'cardio', family: 'conditioning', equipment: 'none', difficulty: 'beginner', reps: '3×30s',
    how: 'Run in place driving knees to hip height, fast arms.',
    cues: ['Stand tall, ribs over hips', 'Drive the knees to hip height, land on the balls of the feet', 'Pump the arms — they set the leg speed'],
    mistake: 'Leaning back to lift the knees, which trades the hip flexors for the lower back.' },
  { id: 'lateralskater', name: 'Skater jumps', muscle: 'cardio', family: 'conditioning', equipment: 'none', difficulty: 'intermediate', reps: '3×20',
    how: 'Bound side to side, landing on one leg and sticking it.',
    cues: ['Push off one leg sideways and land on the other', 'Land soft and hold for a beat before the next bound', 'Let the free leg swing behind for balance'],
    mistake: 'Bounding straight into the next rep, so no landing is ever controlled.' },
  { id: 'bearcrawl', name: 'Bear crawl', muscle: 'full body', family: 'conditioning', equipment: 'none', difficulty: 'intermediate', reps: '3×30s',
    how: 'Hands and toes, knees an inch off the floor, crawl with opposite hand and foot.',
    cues: ['Hands under shoulders, knees under hips and an inch off the floor', 'Move opposite hand and foot together', 'Keep the hips low and level — no rocking side to side'],
    mistake: 'Letting the hips swing, which is the sign the trunk has stopped holding the shape.' },
  { id: 'jumprope', name: 'Jump rope', muscle: 'cardio', family: 'conditioning', equipment: 'rope', difficulty: 'beginner', reps: '5×60s',
    how: 'Small jumps, wrists turning the rope, elbows in at the ribs.',
    cues: ['Elbows at the ribs; the wrists turn the rope, not the arms', 'Jump just high enough to clear it — an inch is plenty', 'Land on the balls of the feet with soft knees'],
    mistake: 'Jumping high and swinging from the shoulders, which ends the set in forty seconds.' },
  { id: 'burpee', name: 'Burpees', muscle: 'full body', family: 'conditioning', equipment: 'none', difficulty: 'intermediate', reps: '3×10',
    how: 'Squat, kick back to a plank, (push-up), jump feet in, jump up.',
    cues: ['Hands down, kick the feet back to a straight plank', 'Chest to the floor if you are doing the push-up version — all or none, not half', 'Jump the feet in under the hips, then stand and jump'],
    mistake: 'Landing in a sagging plank. Drop the push-up before you drop the plank position.' },
  { id: 'dbthruster', name: 'Dumbbell thruster', muscle: 'full body', family: 'conditioning', equipment: 'dumbbell', difficulty: 'advanced', reps: '3×10',
    how: 'Front squat into an overhead press as one movement — the legs start the press.',
    cues: ['Dumbbells at the shoulders, squat to depth with the chest up', 'Drive out of the bottom and let the momentum carry into the press', 'Finish with the arms locked, weights over the ears'],
    mistake: 'Pausing at the top of the squat, which makes it two exercises and twice the work.' },
  { id: 'tricepdip', name: 'Chair tricep dips', muscle: 'arms', family: 'push', equipment: 'chair', difficulty: 'beginner', reps: '3×12',
    how: 'Hands on a chair edge, lower with elbows pointing back, press up.',
    cues: ['Hands on the front edge of a stable seat, fingers forward', 'Elbows point straight back, not out', 'Lower until the upper arms are about parallel with the floor, then press up'],
    mistake: 'Going as deep as the shoulder allows. Parallel is the floor of the range, not the start of it.' },
  { id: 'dbcurl', name: 'Dumbbell curl', muscle: 'arms', family: 'row', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×12',
    how: 'Elbows pinned at the ribs, curl without swinging the body.',
    cues: ['Stand tall, dumbbells at the sides, palms forward', 'Curl with the elbows fixed at the ribs', 'Lower all the way to straight arms over two seconds'],
    mistake: 'Swinging the torso to start each rep, which moves the weight and not the arm.' },
  { id: 'dbhammercurl', name: 'Hammer curl', muscle: 'arms', family: 'row', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×12',
    how: 'Palms facing in the whole way — the thicker-arm version of the curl.',
    cues: ['Palms facing each other, thumbs up, and they stay there', 'Elbows at the ribs, curl to the shoulder', 'Lower fully under control until the arms are straight'],
    mistake: 'Rotating the palms up on the way, which makes it an ordinary curl.' },
  { id: 'dboverheadext', name: 'Overhead triceps extension', muscle: 'arms', family: 'overhead', equipment: 'dumbbell', difficulty: 'beginner', reps: '3×12',
    how: 'One dumbbell behind the head, elbows pointing up, extend to straight.',
    cues: ['Both hands on one dumbbell, elbows up beside the ears', 'Lower behind the head until the triceps stretch', 'Extend to straight without letting the elbows flare out'],
    mistake: 'Letting the elbows drift wide, which hands the lift to the shoulders.' },
  { id: 'bandcurl', name: 'Band curl', muscle: 'arms', family: 'row', equipment: 'band', difficulty: 'beginner', reps: '3×20',
    how: 'Stand on the band, curl the handles — hardest at the top, so squeeze there.',
    cues: ['Both feet on the band, handles at the sides, palms forward', 'Curl to the shoulders and pause where the band is tightest', 'Return slowly against the pull'],
    mistake: 'Letting the band pull the hands down fast, which skips the half of the rep that is free resistance.' },
]
