import { GLYPH_PATHS, type GlyphPaths } from './icon-paths'

/**
 * ICON REGISTRY · the app's icon vocabulary, and the only module that knows how
 * a glyph is drawn.
 *
 * GENERATED by scripts/build-icons.mjs. To add an icon: add the export here,
 * re-run the script, and it picks up the path data.
 *
 * These are Phosphor's glyphs, rebuilt locally at two weights. The published
 * package puts all six weights of a glyph in one module, so tree-shaking cannot
 * drop the four this app never renders — that was ~2/3 of a 413 kB chunk.
 *
 * Names are Phosphor's own, and not always the obvious word (`Prohibit` for a
 * ban, `Lifebuoy` for help, `Sword` for a duel), which is why the mapping is
 * written down rather than remembered.
 *
 * Render through `<Icon as={…} />` — never `<Sun />` directly. The wrapper owns
 * size, weight and the active state; a raw glyph bypasses all three.
 */
export type Icon = (props: {
  size?: string | number
  weight?: 'regular' | 'duotone'
  className?: string
  style?: React.CSSProperties
  'aria-hidden'?: boolean
  'aria-label'?: string
  children?: React.ReactNode
}) => React.ReactElement

function glyph(paths: GlyphPaths): Icon {
  return function Glyph({ size = '1em', weight = 'regular', children, ...rest }) {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        fill="currentColor"
        viewBox="0 0 256 256"
        {...rest}
      >
        {children}
        {(weight === 'duotone' ? paths.d : paths.r).map((p, i) => (
          <path key={i} d={p.d} opacity={p.o} />
        ))}
      </svg>
    )
  }
}

export const Alarm = /* @__PURE__ */ glyph(GLYPH_PATHS.Alarm) // was AlarmClock
export const Archive = /* @__PURE__ */ glyph(GLYPH_PATHS.Archive) // was Archive
export const ArrowClockwise = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowClockwise) // was RotateCw
export const ArrowCounterClockwise = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowCounterClockwise) // was RotateCcw
export const ArrowLineRight = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowLineRight) // was SkipForward
export const ArrowLineUp = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowLineUp) // was ArrowUpToLine
export const ArrowRight = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowRight) // was ArrowRight
export const ArrowsClockwise = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowsClockwise) // was RefreshCw, Repeat
export const ArrowsOut = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowsOut) // was Maximize2
export const ArrowSquareOut = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowSquareOut) // was ExternalLink
export const ArrowsVertical = /* @__PURE__ */ glyph(GLYPH_PATHS.ArrowsVertical) // was MoveVertical
export const At = /* @__PURE__ */ glyph(GLYPH_PATHS.At) // was AtSign
export const Barbell = /* @__PURE__ */ glyph(GLYPH_PATHS.Barbell) // was Dumbbell
export const Bell = /* @__PURE__ */ glyph(GLYPH_PATHS.Bell) // was Bell
export const Bookmark = /* @__PURE__ */ glyph(GLYPH_PATHS.Bookmark) // was Bookmark
export const BookOpen = /* @__PURE__ */ glyph(GLYPH_PATHS.BookOpen) // was BookOpen
export const Books = /* @__PURE__ */ glyph(GLYPH_PATHS.Books) // was BookMarked
export const Brain = /* @__PURE__ */ glyph(GLYPH_PATHS.Brain) // was Brain
export const Cake = /* @__PURE__ */ glyph(GLYPH_PATHS.Cake) // was Cake
export const CalendarBlank = /* @__PURE__ */ glyph(GLYPH_PATHS.CalendarBlank) // was CalendarDays, CalendarRange
export const CalendarCheck = /* @__PURE__ */ glyph(GLYPH_PATHS.CalendarCheck) // was CalendarCheck
export const CalendarDot = /* @__PURE__ */ glyph(GLYPH_PATHS.CalendarDot) // was CalendarClock
export const CalendarPlus = /* @__PURE__ */ glyph(GLYPH_PATHS.CalendarPlus) // was CalendarPlus
export const CalendarX = /* @__PURE__ */ glyph(GLYPH_PATHS.CalendarX) // was CalendarX
export const Camera = /* @__PURE__ */ glyph(GLYPH_PATHS.Camera) // was Camera
export const CaretDoubleDown = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretDoubleDown) // was ChevronsDown
export const CaretDoubleUp = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretDoubleUp) // was ChevronsUp
export const CaretDown = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretDown) // was ChevronDown
export const CaretLeft = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretLeft) // was ChevronLeft
export const CaretRight = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretRight) // was ChevronRight
export const CaretUp = /* @__PURE__ */ glyph(GLYPH_PATHS.CaretUp) // was ChevronUp
export const ChartBar = /* @__PURE__ */ glyph(GLYPH_PATHS.ChartBar) // was BarChart3
export const ChartPie = /* @__PURE__ */ glyph(GLYPH_PATHS.ChartPie) // was PieChart
export const ChatCenteredDots = /* @__PURE__ */ glyph(GLYPH_PATHS.ChatCenteredDots) // was MessageSquarePlus
export const Check = /* @__PURE__ */ glyph(GLYPH_PATHS.Check) // was Check
export const CheckCircle = /* @__PURE__ */ glyph(GLYPH_PATHS.CheckCircle) // was CheckCircle2
export const CheckSquare = /* @__PURE__ */ glyph(GLYPH_PATHS.CheckSquare) // was CheckSquare
export const Circle = /* @__PURE__ */ glyph(GLYPH_PATHS.Circle) // shadcn dropdown-menu radio dot
export const CircleNotch = /* @__PURE__ */ glyph(GLYPH_PATHS.CircleNotch) // shadcn sonner loading spinner
export const ClipboardText = /* @__PURE__ */ glyph(GLYPH_PATHS.ClipboardText) // was ClipboardCheck
export const Clock = /* @__PURE__ */ glyph(GLYPH_PATHS.Clock) // was Clock
export const Cloud = /* @__PURE__ */ glyph(GLYPH_PATHS.Cloud) // was Cloud
export const CloudArrowDown = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudArrowDown) // was CloudDownload
export const CloudArrowUp = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudArrowUp) // was CloudUpload
export const CloudCheck = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudCheck) // was CloudCheck, CloudCog
export const CloudFog = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudFog) // weather: fog
export const CloudLightning = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudLightning) // weather: thunderstorm
export const CloudRain = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudRain) // weather: rain
export const CloudSlash = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudSlash) // was CloudOff
export const CloudSnow = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudSnow) // weather: snow
export const CloudSun = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudSun) // weather: partly cloudy
export const CloudWarning = /* @__PURE__ */ glyph(GLYPH_PATHS.CloudWarning) // was CloudAlert
export const Code = /* @__PURE__ */ glyph(GLYPH_PATHS.Code) // was Code2
export const Columns = /* @__PURE__ */ glyph(GLYPH_PATHS.Columns) // was Columns2
export const Command = /* @__PURE__ */ glyph(GLYPH_PATHS.Command) // was Command
export const Compass = /* @__PURE__ */ glyph(GLYPH_PATHS.Compass) // was Compass
export const Crosshair = /* @__PURE__ */ glyph(GLYPH_PATHS.Crosshair) // was Crosshair
export const Database = /* @__PURE__ */ glyph(GLYPH_PATHS.Database) // was Database
export const DotsSixVertical = /* @__PURE__ */ glyph(GLYPH_PATHS.DotsSixVertical) // was GripVertical
export const DotsThree = /* @__PURE__ */ glyph(GLYPH_PATHS.DotsThree) // was MoreHorizontal
export const Download = /* @__PURE__ */ glyph(GLYPH_PATHS.Download) // was Download
export const Drop = /* @__PURE__ */ glyph(GLYPH_PATHS.Drop) // was CupSoda
export const Envelope = /* @__PURE__ */ glyph(GLYPH_PATHS.Envelope) // was Mail
export const Eye = /* @__PURE__ */ glyph(GLYPH_PATHS.Eye) // was Eye
export const EyeSlash = /* @__PURE__ */ glyph(GLYPH_PATHS.EyeSlash) // was EyeOff
export const FadersHorizontal = /* @__PURE__ */ glyph(GLYPH_PATHS.FadersHorizontal) // was Settings2
export const FileText = /* @__PURE__ */ glyph(GLYPH_PATHS.FileText) // was FileText
export const Flag = /* @__PURE__ */ glyph(GLYPH_PATHS.Flag) // was Flag
export const Flame = /* @__PURE__ */ glyph(GLYPH_PATHS.Flame) // was Flame
export const Flower = /* @__PURE__ */ glyph(GLYPH_PATHS.Flower) // was Flower2
export const FolderOpen = /* @__PURE__ */ glyph(GLYPH_PATHS.FolderOpen) // was FolderOpen
export const Footprints = /* @__PURE__ */ glyph(GLYPH_PATHS.Footprints) // was Footprints
export const ForkKnife = /* @__PURE__ */ glyph(GLYPH_PATHS.ForkKnife) // was Utensils
export const Gauge = /* @__PURE__ */ glyph(GLYPH_PATHS.Gauge) // was Gauge
export const Gear = /* @__PURE__ */ glyph(GLYPH_PATHS.Gear) // was Cog
export const GitBranch = /* @__PURE__ */ glyph(GLYPH_PATHS.GitBranch) // was GitBranch
export const GraduationCap = /* @__PURE__ */ glyph(GLYPH_PATHS.GraduationCap) // was GraduationCap
export const GridFour = /* @__PURE__ */ glyph(GLYPH_PATHS.GridFour) // was Grid3x3
export const HandFist = /* @__PURE__ */ glyph(GLYPH_PATHS.HandFist) // was HandMetal
export const HardDrive = /* @__PURE__ */ glyph(GLYPH_PATHS.HardDrive) // was HardDrive
export const Hash = /* @__PURE__ */ glyph(GLYPH_PATHS.Hash) // was Hash
export const Heart = /* @__PURE__ */ glyph(GLYPH_PATHS.Heart) // was Heart
export const Heartbeat = /* @__PURE__ */ glyph(GLYPH_PATHS.Heartbeat) // was HeartPulse
export const Hourglass = /* @__PURE__ */ glyph(GLYPH_PATHS.Hourglass) // was Hourglass
export const Image = /* @__PURE__ */ glyph(GLYPH_PATHS.Image) // was Image
export const Info = /* @__PURE__ */ glyph(GLYPH_PATHS.Info) // was Info
export const Keyboard = /* @__PURE__ */ glyph(GLYPH_PATHS.Keyboard) // was Keyboard
export const Lifebuoy = /* @__PURE__ */ glyph(GLYPH_PATHS.Lifebuoy) // was LifeBuoy
export const Lightbulb = /* @__PURE__ */ glyph(GLYPH_PATHS.Lightbulb) // was Lightbulb
export const Link = /* @__PURE__ */ glyph(GLYPH_PATHS.Link) // was Link2
export const List = /* @__PURE__ */ glyph(GLYPH_PATHS.List) // was Menu
export const ListChecks = /* @__PURE__ */ glyph(GLYPH_PATHS.ListChecks) // was ListChecks, ListTodo
export const ListNumbers = /* @__PURE__ */ glyph(GLYPH_PATHS.ListNumbers) // was ListOrdered
export const Lock = /* @__PURE__ */ glyph(GLYPH_PATHS.Lock) // was Lock
export const MagnifyingGlass = /* @__PURE__ */ glyph(GLYPH_PATHS.MagnifyingGlass) // was Search
export const MapPin = /* @__PURE__ */ glyph(GLYPH_PATHS.MapPin) // was MapPin
export const Medal = /* @__PURE__ */ glyph(GLYPH_PATHS.Medal) // was Award, Medal
export const Microphone = /* @__PURE__ */ glyph(GLYPH_PATHS.Microphone) // was Mic
export const MicrophoneSlash = /* @__PURE__ */ glyph(GLYPH_PATHS.MicrophoneSlash) // was MicOff
export const Minus = /* @__PURE__ */ glyph(GLYPH_PATHS.Minus) // was Minus
export const Moon = /* @__PURE__ */ glyph(GLYPH_PATHS.Moon) // was Moon
export const MoonStars = /* @__PURE__ */ glyph(GLYPH_PATHS.MoonStars) // time-of-day: evening
export const Note = /* @__PURE__ */ glyph(GLYPH_PATHS.Note) // was StickyNote
export const NotePencil = /* @__PURE__ */ glyph(GLYPH_PATHS.NotePencil) // was NotebookPen
export const Palette = /* @__PURE__ */ glyph(GLYPH_PATHS.Palette) // was Palette
export const Pause = /* @__PURE__ */ glyph(GLYPH_PATHS.Pause) // was Pause
export const PencilSimple = /* @__PURE__ */ glyph(GLYPH_PATHS.PencilSimple) // was PenLine
export const Person = /* @__PURE__ */ glyph(GLYPH_PATHS.Person) // was PersonStanding
export const PersonSimpleRun = /* @__PURE__ */ glyph(GLYPH_PATHS.PersonSimpleRun) // was Activity
export const PiggyBank = /* @__PURE__ */ glyph(GLYPH_PATHS.PiggyBank) // was PiggyBank
export const Play = /* @__PURE__ */ glyph(GLYPH_PATHS.Play) // was Play
export const Plus = /* @__PURE__ */ glyph(GLYPH_PATHS.Plus) // was Plus
export const Prohibit = /* @__PURE__ */ glyph(GLYPH_PATHS.Prohibit) // was Ban
export const Question = /* @__PURE__ */ glyph(GLYPH_PATHS.Question) // was HelpCircle
export const RadioButton = /* @__PURE__ */ glyph(GLYPH_PATHS.RadioButton) // was CircleDot
export const Scales = /* @__PURE__ */ glyph(GLYPH_PATHS.Scales) // was Scale
export const ShareNetwork = /* @__PURE__ */ glyph(GLYPH_PATHS.ShareNetwork) // was Share2
export const Shield = /* @__PURE__ */ glyph(GLYPH_PATHS.Shield) // was Shield
export const ShieldCheck = /* @__PURE__ */ glyph(GLYPH_PATHS.ShieldCheck) // was ShieldCheck
export const ShieldPlus = /* @__PURE__ */ glyph(GLYPH_PATHS.ShieldPlus) // was ShieldPlus
export const ShieldWarning = /* @__PURE__ */ glyph(GLYPH_PATHS.ShieldWarning) // was ShieldAlert
export const Sidebar = /* @__PURE__ */ glyph(GLYPH_PATHS.Sidebar) // was PanelLeft, PanelLeftOpen
export const SidebarSimple = /* @__PURE__ */ glyph(GLYPH_PATHS.SidebarSimple) // was PanelLeftClose
export const SignIn = /* @__PURE__ */ glyph(GLYPH_PATHS.SignIn) // was LogIn
export const SignOut = /* @__PURE__ */ glyph(GLYPH_PATHS.SignOut) // was LogOut
export const SlidersHorizontal = /* @__PURE__ */ glyph(GLYPH_PATHS.SlidersHorizontal) // was Settings, SlidersHorizontal
export const Smiley = /* @__PURE__ */ glyph(GLYPH_PATHS.Smiley) // was Smile
export const Sparkle = /* @__PURE__ */ glyph(GLYPH_PATHS.Sparkle) // was Sparkles
export const Square = /* @__PURE__ */ glyph(GLYPH_PATHS.Square) // was Square
export const SquaresFour = /* @__PURE__ */ glyph(GLYPH_PATHS.SquaresFour) // was LayoutGrid
export const Stack = /* @__PURE__ */ glyph(GLYPH_PATHS.Stack) // was Layers
export const Star = /* @__PURE__ */ glyph(GLYPH_PATHS.Star) // was Star
export const Sun = /* @__PURE__ */ glyph(GLYPH_PATHS.Sun) // was Sun
export const SunHorizon = /* @__PURE__ */ glyph(GLYPH_PATHS.SunHorizon) // time-of-day: morning
export const Sword = /* @__PURE__ */ glyph(GLYPH_PATHS.Sword) // was Swords
export const Target = /* @__PURE__ */ glyph(GLYPH_PATHS.Target) // was Target
export const Thermometer = /* @__PURE__ */ glyph(GLYPH_PATHS.Thermometer) // weather: unknown code
export const Timer = /* @__PURE__ */ glyph(GLYPH_PATHS.Timer) // was Timer
export const Trash = /* @__PURE__ */ glyph(GLYPH_PATHS.Trash) // was Trash2
export const TrendDown = /* @__PURE__ */ glyph(GLYPH_PATHS.TrendDown) // was TrendingDown
export const TrendUp = /* @__PURE__ */ glyph(GLYPH_PATHS.TrendUp) // was TrendingUp
export const Trophy = /* @__PURE__ */ glyph(GLYPH_PATHS.Trophy) // was Trophy
export const Upload = /* @__PURE__ */ glyph(GLYPH_PATHS.Upload) // was Upload
export const User = /* @__PURE__ */ glyph(GLYPH_PATHS.User) // was UserRound
export const UserCircle = /* @__PURE__ */ glyph(GLYPH_PATHS.UserCircle) // was UserCircle2
export const UserPlus = /* @__PURE__ */ glyph(GLYPH_PATHS.UserPlus) // was UserPlus
export const Users = /* @__PURE__ */ glyph(GLYPH_PATHS.Users) // was Users
export const Video = /* @__PURE__ */ glyph(GLYPH_PATHS.Video) // was Video
export const Warning = /* @__PURE__ */ glyph(GLYPH_PATHS.Warning) // was AlertTriangle
export const Wind = /* @__PURE__ */ glyph(GLYPH_PATHS.Wind) // was Wind
export const X = /* @__PURE__ */ glyph(GLYPH_PATHS.X) // was X
export const XCircle = /* @__PURE__ */ glyph(GLYPH_PATHS.XCircle) // shadcn sonner error
