/**
 * Generate a two-weight icon module from Phosphor's own path data.
 *
 * Phosphor ships every glyph as one module containing all six weights — thin,
 * light, regular, bold, fill, duotone — in a single Map, so tree-shaking cannot
 * reach the five this app never renders. Measured: 413 kB raw / 93 kB gzip for
 * 152 glyphs, of which roughly two thirds is unreachable dead weight. Importing
 * per-icon entrypoints instead produced a byte-identical chunk, so the layout of
 * the package, not the import style, is the cost.
 *
 * This reads the installed package's own defs at build time and emits only the
 * two weights the icon system uses (`regular` at rest, `duotone` when active),
 * as plain path data. No hand-copied SVG: the source of truth stays the
 * dependency, and re-running this after an upgrade picks up its changes.
 *
 *     node scripts/build-icons.mjs
 *
 * Output:
 *   src/components/icon-paths.ts  — path data
 *   src/components/icons.tsx      — the registry: one named export per glyph
 *
 * The glyph list is read from the existing registry, so adding an icon stays a
 * one-line edit there followed by a re-run of this script.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const REGISTRY = join(root, 'src/components/icons.tsx')
const DEFS = join(root, 'node_modules/@phosphor-icons/react/dist/defs')
const OUT = join(root, 'src/components/icon-paths.ts')

// Names come from the registry's own export list.
const registrySrc = readFileSync(REGISTRY, 'utf8')
const names = [...registrySrc.matchAll(/^\s{2}([A-Z][A-Za-z0-9]*),/gm)].map((m) => m[1])
if (names.length === 0) throw new Error('no glyph names found in the registry')

/**
 * Pull one weight's `<path>` attributes out of a defs module.
 *
 * The defs are minified ESM that build React elements, so this reads them as
 * text rather than importing them: the shape is stable (`["<weight>", …
 * createElement("path", { d: "…", opacity: "0.2" }) …]`) and text-scraping keeps
 * the script free of a React runtime.
 */
function extractWeight(source, weight) {
  const start = source.indexOf(`"${weight}"`)
  if (start === -1) return null
  // Each weight entry ends where the next array element begins.
  const rest = source.slice(start)
  const end = rest.search(/\n\s*\],?\n\s*\[/)
  const block = end === -1 ? rest : rest.slice(0, end)
  const paths = []
  for (const m of block.matchAll(/\{\s*d:\s*"([^"]+)"(?:,\s*opacity:\s*"([^"]+)")?\s*\}/g)) {
    paths.push(m[2] ? { d: m[1], o: m[2] } : { d: m[1] })
  }
  return paths.length ? paths : null
}

const out = {}
const missing = []
for (const name of names) {
  const file = join(DEFS, `${name}.es.js`)
  if (!existsSync(file)) {
    missing.push(name)
    continue
  }
  const src = readFileSync(file, 'utf8')
  const regular = extractWeight(src, 'regular')
  const duotone = extractWeight(src, 'duotone')
  if (!regular || !duotone) {
    missing.push(name)
    continue
  }
  out[name] = { r: regular, d: duotone }
}

if (missing.length) throw new Error(`could not extract: ${missing.join(', ')}`)

const banner = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
//
// Only the two weights this app renders: \`r\` = regular (rest), \`d\` = duotone
// (active). Phosphor ships six per glyph in one module, which tree-shaking
// cannot split, so the other four were ~2/3 of a 413 kB chunk.
//
// Re-run the script after upgrading @phosphor-icons/react.

export type GlyphPath = { d: string; o?: string }
export type GlyphPaths = { r: GlyphPath[]; d: GlyphPath[] }

export const GLYPH_PATHS: Record<string, GlyphPaths> = `

writeFileSync(OUT, banner + JSON.stringify(out) + '\n', 'utf8')
const kb = (readFileSync(OUT).length / 1024).toFixed(0)

// The registry: one named export per glyph, built from the data above.
const notes = new Map(
  [...registrySrc.matchAll(/^\s{2}([A-Z][A-Za-z0-9]*),\s*\/\/ (.+)$/gm)].map((m) => [m[1], m[2]]),
)
const header = `import { GLYPH_PATHS, type GlyphPaths } from './icon-paths'

/**
 * ICON REGISTRY · the app's icon vocabulary, and the only module that knows how
 * a glyph is drawn.
 *
 * GENERATED by scripts/build-icons.mjs. To add an icon: add the export here,
 * re-run the script, and it picks up the path data.
 *
 * These are Phosphor's glyphs, rebuilt locally at two weights. The published
 * package puts all six weights of a glyph in one module, so tree-shaking cannot
 * drop the four this app never renders — that was ~2/3 of a 413 kB chunk.
 *
 * Names are Phosphor's own, and not always the obvious word (\`Prohibit\` for a
 * ban, \`Lifebuoy\` for help, \`Sword\` for a duel), which is why the mapping is
 * written down rather than remembered.
 *
 * Render through \`<Icon as={…} />\` — never \`<Sun />\` directly. The wrapper owns
 * size, weight and the active state; a raw glyph bypasses all three.
 */
export type Icon = (props: {
  size?: string | number
  weight?: 'regular' | 'duotone'
  className?: string
  style?: React.CSSProperties
  'aria-hidden'?: boolean
  'aria-label'?: string
  children?: React.ReactNode
}) => React.ReactElement

function glyph(paths: GlyphPaths): Icon {
  return function Glyph({ size = '1em', weight = 'regular', children, ...rest }) {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        fill="currentColor"
        viewBox="0 0 256 256"
        {...rest}
      >
        {children}
        {(weight === 'duotone' ? paths.d : paths.r).map((p, i) => (
          <path key={i} d={p.d} opacity={p.o} />
        ))}
      </svg>
    )
  }
}

`
const exports = names
  .map((n) => {
    const note = notes.get(n)
    return `export const ${n} = /* @__PURE__ */ glyph(GLYPH_PATHS.${n})${note ? ` // ${note}` : ''}`
  })
  .join('\n')
writeFileSync(REGISTRY, header + exports + '\n', 'utf8')
console.log(`wrote ${OUT} — ${names.length} glyphs, ${kb} kB of path data`)
console.log(`wrote ${REGISTRY} — ${names.length} exports`)
