import { Sparkle, Trash } from '@/components/icons'
import { Icon } from '@/components/Icon'
import { useJournal } from '../../store'
import { Card } from '../ui'
import { Button } from '../ui/button'
import { Switch } from '../ui/switch'
import { useConfirm } from '../ConfirmDialog'
import { notify } from '../../lib/notify'
import { todayISO } from '../../lib/date'
import { emptyJournal, exportJSON } from '../../lib/storage'
import { stripSyncSecrets } from '../../lib/csv'
import { generateDemoData } from '../../lib/demo'
import { inlineImages } from '../../lib/imageStore'
import { download } from './download'

/**
 * Sample data, and the danger zone. The only card in Settings that can destroy
 * a journal, which is why every button here routes through `confirm` with an
 * `onBackup` offer — except "Remove demo data", deliberately: the samples are
 * generated from a fixed seed in `lib/demo.ts`, so offering to download a copy
 * would imply they are yours and worth keeping.
 */
export function DemoResetCard() {
  const confirm = useConfirm()
  const { data, setSettings, replaceAll } = useJournal()

  async function doExport() {
    const full = await inlineImages(data)
    download(`cadence-backup-${todayISO()}.json`, exportJSON(stripSyncSecrets(full)))
    setSettings({ lastBackup: todayISO() })
  }

  return (
      <Card band title="Demo & reset" subtitle="Sample data, or start fresh">
        <div className="flex flex-wrap gap-2">
          {/* Hidden, not disabled, when demo data is switched off: a greyed
              button invites a click and then explains why it will not work.
              The switch below is the place that answers "why is this gone". */}
          {!data.settings.demoDisabled && (
          <Button
            variant="secondary"
            onClick={async () => {
              if (data.entries.length === 0 || await confirm({
                title: 'Load demo data?',
                description: 'This replaces your current journal with about 30 days of sample entries.',
                confirmLabel: 'Load demo data', destructive: true, onBackup: doExport,
              })) {
                replaceAll(generateDemoData())
              }
            }}
            className="inline-flex items-center gap-1.5"
          >
            <Icon as={Sparkle} size="sm" /> Load demo data
          </Button>
          )}
          {/* Only offered when the journal actually IS the samples. Without the
              marker this button could not exist: nothing distinguishes a demo
              entry from a real one, so "remove the demo" on a journal that has
              since been written in would have meant erasing the real work too.
              That is why the confirm still names the counts — anything typed
              since the seed goes with it. */}
          {data.settings.demoSeeded && (
          <Button
            variant="secondary"
            onClick={async () => {
              if (await confirm({
                title: 'Remove the demo data?',
                description: `This journal was filled with samples. Removing them clears all ${data.entries.length} entries and starts you on an empty journal — including anything you have added since.`,
                // No `onBackup`, unlike every other destructive action here.
                // Demo data is generated by `lib/demo.ts` from a fixed seed —
                // it is in the code, reproducible on demand, and identical for
                // everyone. Offering to download a copy of it implies it is
                // yours and worth keeping, which is the opposite of what this
                // button is for.
                confirmLabel: 'Remove the samples', destructive: true,
              })) {
                replaceAll(emptyJournal())
                setSettings({ storageMode: 'local', demoSeeded: false, explore: false })
                notify.success('Demo data removed', 'You are starting from an empty journal.')
              }
            }}
            className="inline-flex items-center gap-1.5"
          >
            <Icon as={Trash} size="sm" /> Remove demo data
          </Button>
          )}
          <Button
            variant="danger"
            onClick={async () => {
              if (await confirm({
                title: 'Erase everything and start fresh?',
                description: `This deletes all ${data.entries.length} entries, ${data.habits.length} habits, ${data.workouts.length} workouts, and every photo and memory on this device. It cannot be undone.`,
                confirmLabel: 'Erase everything', destructive: true, onBackup: doExport,
              })) {
                replaceAll(emptyJournal())
              }
            }}
            className="inline-flex items-center gap-1.5"
          >
            <Icon as={Trash} size="sm" /> Clear all data
          </Button>
          <Button
            variant="secondary"
            onClick={async () => { if (await confirm({
              title: 'Return to the start screen?',
              description: 'Your data is kept, and you can choose guest, account, or device again.',
              confirmLabel: 'Go to start screen',
            })) setSettings({ storageMode: undefined }) }}
            className="inline-flex items-center gap-1.5"
          >
            Back to start screen
          </Button>
        </div>
        <label className="mt-4 flex cursor-pointer items-center justify-between gap-4 border-t border-line pt-3 text-body text-fg-1">
          <span>
            Allow demo data
            <span className="block text-label text-fg-2">
              Off: <code>?demo=1</code> links are ignored and the sample journal cannot be loaded. If this journal is samples, you are asked whether to clear them too.
            </span>
          </span>
          <Switch
            checked={!data.settings.demoDisabled}
            onCheckedChange={async (on) => {
              setSettings({ demoDisabled: !on })
              if (on) {
                notify.success('Demo data allowed', 'You can load the sample journal again.')
                return
              }
              // Switching it off only stopped *future* seeding, which is not
              // what "disable demo data" means to someone looking at a journal
              // full of samples. If this journal is the samples, offer to clear
              // them in the same gesture rather than leaving the switch looking
              // like it did nothing.
              if (!data.settings.demoSeeded) {
                notify.success('Demo data switched off', 'Sample data can no longer be loaded.')
                return
              }
              if (await confirm({
                title: 'Clear the samples already loaded?',
                description: `New samples can no longer load. This journal is still holding ${data.entries.length} of them — clearing now starts you on an empty journal, including anything you have added since.`,
                confirmLabel: 'Clear them now',
                cancelLabel: 'Keep them for now',
                destructive: true,
              })) {
                replaceAll(emptyJournal())
                setSettings({ storageMode: 'local', demoSeeded: false, explore: false, demoDisabled: true })
                notify.success('Demo data removed', 'You are starting from an empty journal.')
              } else {
                notify.info('Demo data switched off', 'The samples already here are untouched; you can remove them any time.')
              }
            }}
          />
        </label>
        <p className="mt-2 text-label text-fg-2">
          Demo data fills ~30 days of correlated entries so charts have something to show. <strong>Back to start screen</strong> keeps your data and lets you re-pick how it's stored; <strong>Clear all data</strong> wipes everything.
        </p>
      </Card>
  )
}
